# include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Ref: https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # for code clarity (speed of reading) we always want to specify types
    always_specify_types: true
    omit_local_variable_types: false
