name: saropa_dart_utils
description: "Boilerplate reduction tools and human readable extension methods by Saropa"
version: 0.3.11+Jakarta

homepage: https://app.saropa.com
repository: https://github.com/saropa/saropa_dart_utils
issue_tracker: https://github.com/saropa/saropa_dart_utils/issues
documentation: https://pub.dev/documentation/saropa_dart_utils/latest/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  # Contains utility functions and classes in the style of dart:collection to make working with collections easier.
  # https://pub.dev/packages/collection/changelog
  # NOTE: Because every version of flutter_test from sdk depends on collection 1.18.0 and saropa depends on collection ^1.19.0, flutter_test from sdk is forbidden.
  collection: ^1.18.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # This package contains a recommended set of lints for Flutter apps, packages, and plugins to encourage good coding practices.
  # https://pub.dev/packages/flutter_lints/changelog
  # flutter_lints: ^3.0.1

  # This package provides lint rules for Dart and Flutter which are used at Very Good Ventures. For more information, see the complete list of options.
  # https://pub.dev/packages/very_good_analysis/changelog
  very_good_analysis: ">=6.0.0 <8.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
