# This is an example workflow to upload coverage reports to Codecov

name: Codecov

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "codecov"
  codecov:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a script to generate a coverage report
      - name: Generate coverage report
        run: |
          # Replace this with your own commands to generate a coverage report
          # For example, you can use coverage.py or pytest-cov for Python projects
          coverage run -m unittest discover
          coverage xml

      # Uploads coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: saropa/saropa_dart_utils
